### ISSUE TITLE
Debian Buster : Can't compile, SDL_image.h absent

### ISSUE THREAD

**Issue by pouek** [wolfschus/arturiagang#1]
Hello,
Cool to see your project, and too bad nobody helps, so here I am :)
I tried to compile following your readme guidelines but I get this error 
`SDL/SDL_image.h: No such file`
I found that this file is indeed absent, and could finally compile having installed `libsdl-image1.2-dev`
You may want to add it to your `apt install` command.

Also I wasn't sure you wrote correctly the last 2 (make) commands : 
`make setup sudo make install`
did you mean
`make`
`setup`
`sudo make install`
or in one line 
`make && setup && sudo make install` 
?
thanks

**Comment by wolfschus** [comment]
Hello,

thank you very much.
As you see at the answertime, I have no time at the moment to work on this project.
You are welcome to work on it.

Kind Regards
Wolf
